#!/usr/bin/env bash

yarn --version
if which sudo; then
  if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
  export DEV_NULL="/dev/null"
else
  # windows most likely
  export SUDO=""
  # /dev/null doesn't exist on windows;
  # NUL is the windows equivalent
  export DEV_NULL="NUL"
fi

# FUNCTIONS
get_yarn_version () {
  if [[ $YARN_VERSION == "" ]]; then
    YARN_ORB_VERSION=$(curl -Ls -o "${DEV_NULL}" -w %{url_effective} \
      "https://github.com/yarnpkg/yarn/releases/latest" | sed 's:.*/::' | cut -d 'v' -f 2 | cut -d 'v' -f 2)
    echo "Latest version of Yarn is $YARN_ORB_VERSION"
  else
    YARN_ORB_VERSION=$YARN_VERSION

    echo "Selected version of Yarn is $YARN_ORB_VERSION"
  fi
}

get_yarn_version

echo "Verifying YARN install"
if yarn --version | grep "$YARN_ORB_VERSION" > "${DEV_NULL}" 2>&1; then
  echo "Success! Yarn $(yarn --version) has been installed to $(which yarn)"
else
  echo "Something went wrong; the specified version of Yarn could not be installed"
  exit 1
fi